version: '2'

services:
  db:
    image: postgres:9.6.2
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    image: thinking-cap:0.1
    tty: true
    command: bash
    volumes:
      - ./thinking-cap:/thinking-cap
    ports:
      - "80:80"
    depends_on:
      - db
